# Make sure /etc/nginx/conf.d/mod-http-passenger.conf also exists which specifies
# passenger_root + passenger_ruby settings.
#
server {
    listen 80;
    listen [::]:80;

    server_name redmine.sassafras.coop;

    # Path to the public folder of the code.
    root /home/deploy/redmine/current/public;

    access_log /var/log/nginx/redmine.access.log;
    error_log  /var/log/nginx/redmine.error.log;

    passenger_enabled on;
    passenger_app_env production;

    client_max_body_size 50m;

    # Redirect server error pages to the static page /50x.html
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root html;
    }
}
